import os

REORIENT_NET_EPOCHS = os.getenv("REORIENT_NET_EPOCHS", 100)
REORIENT_NET_LEARNING_RATE = os.getenv("REORIENT_NET_LEARNING_RATE", 0.001)
REORIENT_NET_BATCH_SIZE = os.getenv("REORIENT_NET_BATCH_SIZE", 64)
REORIENT_NET_LOOKBACK = os.getenv("REORIENT_NET_LOOKBACK", 20)

REORIENT_NET_LSTM_1 = os.getenv("REORIENT_NET_LSTM_1", 100)
REORIENT_NET_LSTM_2 = os.getenv("REORIENT_NET_LSTM_2", 100)
REORIENT_NET_FC_1 = os.getenv("REORIENT_NET_F1", 100)
REORIENT_NET_FC_2 = os.getenv("REORIENT_NET_F2", 100)

ACTIVATION = os.getenv("ACTIVATION", "tanh")